routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\Auth\LoginController::class, 'showLoginForm'])->name('login');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::prefix('admin')->group(function () {
        Route::resource('roles', RoleController::class);
        Route::resource('users', UserController::class);
        Route::resource('permissions', PermissionController::class);
    });
    Route::resource('products', ProductController::class);
});

app/Models/Permission.php
<?php
  
namespace App\Models;
  
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\User;
  
class Permission extends Model
{
    use HasFactory;
  
    /**
     * The attributes that are mass assignable.
     *	
     * @var array
     */
    protected $fillable = [
        'name', 'guard_name', 'user_id'
    ];
    
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }
}

app/Http/Controllers/PermissionController.php
<?php
    
namespace App\Http\Controllers;
    
use App\Models\Permission;
use Illuminate\Http\Request;
    
class PermissionController extends Controller
{ 
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:permission-list|permission-create|permission-edit|permission-delete', ['only' => ['index','show']]);
         $this->middleware('permission:permission-create', ['only' => ['create','store']]);
         $this->middleware('permission:permission-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:permission-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::leftJoin('users', 'permissions.user_id', '=', 'users.id')->orderBy('permissions.id','DESC')
            ->select('permissions.*', 'users.name AS editor')->paginate(10);
        return view('admin.permissions.index',compact('permissions'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.permissions.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'guard_name' => 'required',
        ]);
        $input  = $request->all();
        $input['user_id'] = auth()->user()->id;
    
        Permission::create($input);
    
        return redirect()->route('permissions.index')
                        ->with('success','Permissions created successfully.');
    }
    
    /**
     * Display the specified resource.
     *
     * @param  \App\Permissions  $permission
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $permission = Permission::find($id)->leftJoin('users AS u', 'permissions.user_id', '=', 'u.id')
            ->select('permissions.*', 'u.name AS editor')->first();
        return view('admin.permissions.show',compact('permission'));
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Permissions  $permission
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
        return view('admin.permissions.edit',compact('permission'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Permissions  $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {
        request()->validate([
            'name' => 'required',
            'guard_name' => 'required',
        ]);
        $input  = $request->all();
        $input['user_id'] = auth()->user()->id;
    
        $permission->update($input);
    
        return redirect()->route('permissions.index')
                        ->with('success','Permissions updated successfully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Permissions  $permission
     * @return \Illuminate\Http\Response
     */
    public function destroy(Permission $permission)
    {
        $permission->delete();
    
        return redirect()->route('permissions.index')
                        ->with('success','Permissions deleted successfully');
    }
}

resources/views/admin/permissions/create.blade.php
@extends('layouts.app')


@section('content')

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 margin-tb">
            <div class="float-start">
                <h2>Add New Permission</h2>
            </div>
            <div class="float-end">
                <a class="btn btn-secondary" href="{{ route('permissions.index') }}"> Back</a>
            </div>
        </div>
        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <div class="col-xl-9">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body">
                    {!! Form::open(array('route' => 'permissions.store','method'=>'POST')) !!}
                        <div class="row align-items-center pt-2 pb-3">
                            <div class="col-md-3 ps-5">
                                <h6 class="mb-0">Name</h6>
                            </div>
                            <div class="col-md-9 pe-5">
                                <input type="text" name="name" class="form-control form-control-lg" placeholder="Name">
                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">
                                <h6 class="mb-0">GuardName</h6>
                            </div>
                            <div class="col-md-9 pe-5">
                                <input type="text" name="guard_name" class="form-control form-control-lg" placeholder="GuardName">
                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="px-5 py-4 text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/permissions/edit.blade.php
@extends('layouts.app')


@section('content')
<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 margin-tb">
            <div class="float-start">
                <h2>Edit Permission</h2>
            </div>
            <div class="float-end">
                <a class="btn btn-secondary" href="{{ route('permissions.index') }}"> Back</a>
            </div>
        </div>
        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <div class="col-xl-9">
            <div class="card" style="border-radius: 15px;">
                <div class="card-body">
                    {!! Form::model($permission, ['method' => 'PATCH','route' => ['permissions.update', $permission->id]]) !!}
                        <div class="row align-items-center pt-2 pb-3">
                            <div class="col-md-3 ps-5">
                                <h6 class="mb-0">Name</h6>
                            </div>
                            <div class="col-md-9 pe-5">
                                <input type="text" name="name" value="{{ $permission->name }}" class="form-control form-control-lg" placeholder="Name">
                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">
                                <h6 class="mb-0">GuardName</h6>
                            </div>
                            <div class="col-md-9 pe-5">
                                <input type="text" name="guard_name" value="{{ $permission->guard_name }}" class="form-control form-control-lg" placeholder="GuardName">
                            </div>
                        </div>

                        <hr class="mx-n3">

                        <div class="px-5 py-4 text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/permissions/index.blade.php
@extends('layouts.app')


@section('content')
<div class="card p-0">
    <div class="card-body">
        <h5 class="card-title vh-25">
            <div class="float-start fs-4">
                Permission Management
            </div>
            <div class="float-end">
                <a class="btn btn-success" href="{{ route('permissions.create') }}"> Create</a>
            </div>
        </h5>
    </div>
    <div class="card-body">
        @if ($message = Session::get('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ $message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        @endif
        <!-- Table with stripped rows -->
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="col-md-2">No</th>
                    <th class="col-md-3">Name</th>
                    <th class="col-md-3">GuardName</th>
                    <th class="col-md-2">Editor</th>
                    <th class="col-md-2">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($permissions as $permission)
        	    <tr>
        	        <td>{{ ++$i }}</td>
        	        <td>{{ $permission->name }}</td>
        	        <td>{{ $permission->guard_name }}</td>
        	        <td>{{ $permission->editor }}</td>
        	        <td>
                        <form action="{{ route('permissions.destroy',$permission->id) }}" method="POST">
                            <a class="btn btn-info" href="{{ route('permissions.show',$permission->id) }}"><i class="bi bi-eye h5"></i></a>
                            @can('permission-edit')
                            <a class="btn btn-primary" href="{{ route('permissions.edit',$permission->id) }}"><i class="bi bi-pencil-square h5"></i></a>
                            @endcan

                            @csrf
                            @method('DELETE')
                            @can('permission-delete')
                            <button type="submit" class="btn btn-danger show-alert-delete-box"><i class="bi bi-trash3 h5"></i></button>
                            @endcan
                        </form>
        	        </td>
        	    </tr>
        	    @endforeach
            </tbody>
        </table>
        <!-- End Table with stripped rows -->
    </div>
</div>

{!! $permissions->render() !!}

@endsection

resources/views/admin/permissions/show.blade.php
@extends('layouts.app')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="float-start">
                <h2> Show Product</h2>
            </div>
            <div class="float-end">
                <a class="btn btn-primary" href="{{ route('permissions.index') }}"> Back</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $permission->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>GuardName:</strong>
                {{ $permission->guard_name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Editor:</strong>
                {{ $permission->editor }}
            </div>
        </div>
    </div>
@endsection